version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8000
      - 8001
    ports:
      - 8000:8000
      - 8001:8001
    env_file:
      - .env
    volumes:
      - ./backend/src:/app
    depends_on:
      - db
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 8443:443
    env_file:
      - .env
    networks:
      - mynetwork

  db:
    image: postgres:latest
    container_name: db
    expose:
      - 5432
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    command: postgres -c listen_addresses=*

networks:
  mynetwork:
    driver: bridge
