# Generated by Django 4.2.7 on 2023-12-11 00:54

import authentification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=authentification.models.default_profile_image_path, null=True, upload_to='profile_images/'),
        ),
    ]
