# Generated by Django 4.2.7 on 2023-12-20 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('player1_id', models.IntegerField(default=0)),
                ('player_1_name', models.CharField(max_length=20)),
                ('player_2_name', models.CharField(max_length=20)),
                ('player2_id', models.IntegerField(default=0)),
                ('ball_pos_x', models.FloatField(default=0)),
                ('ball_pos_y', models.FloatField(default=0)),
                ('p1_pos', models.FloatField(default=0)),
                ('p2_pos', models.FloatField(default=0)),
                ('score_p1', models.PositiveIntegerField(default=0)),
                ('score_p2', models.PositiveBigIntegerField(default=0)),
                ('winner_id', models.PositiveBigIntegerField(default=0)),
                ('loser_id', models.PositiveBigIntegerField(default=0)),
                ('map', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('finished', 'Finished'), ('pause', 'Pause')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='current_game_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='master_user_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='player_slots',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('room_id', models.PositiveBigIntegerField(default=0)),
                ('slot', models.PositiveBigIntegerField(default=0)),
                ('is_connected', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='players_connected',
            field=models.ManyToManyField(related_name='connected_rooms', to='game.player'),
        ),
    ]
