# Generated by Django 4.2.7 on 2023-12-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_room_current_game_id_room_game_started_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_connected',
        ),
        migrations.RemoveField(
            model_name='player',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='room',
            name='current_game_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='game_started',
        ),
        migrations.RemoveField(
            model_name='room',
            name='master_user_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player_slots',
        ),
        migrations.RemoveField(
            model_name='room',
            name='players_connected',
        ),
        migrations.AddField(
            model_name='room',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
    ]
