# Generated by Django 4.2.7 on 2023-12-25 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_player_is_connected_remove_player_room_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
