# Generated by Django 4.2.7 on 2023-12-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_room_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='players',
        ),
    ]
