# Generated by Django 4.2.7 on 2023-12-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_room_player_1_room_player_2_room_player_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='connected_users',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player_2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player_3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player_4',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player_5',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player_6',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player_7',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player_8',
        ),
        migrations.AddField(
            model_name='room',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='player_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='players_connected',
            field=models.ManyToManyField(related_name='connected_rooms', to='game.player'),
        ),
    ]
