# Generated by Django 4.2.7 on 2023-12-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_room_connected_users_remove_room_player_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='player_slots',
            field=models.JSONField(default=dict),
        ),
    ]
