# Generated by Django 4.2.7 on 2023-12-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_room_player_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slot',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
