# Generated by Django 4.2.7 on 2023-12-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_player_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='slot',
        ),
    ]
