# Generated by Django 4.2.7 on 2023-12-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_remove_player_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slot',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
