# Generated by Django 4.2.7 on 2023-12-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='score',
        ),
        migrations.AddField(
            model_name='game',
            name='score_p1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='score_p2',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='current_game_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='ball_pos_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='ball_pos_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='p1_pos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='p2_pos',
            field=models.FloatField(default=0),
        ),
    ]
