# Generated by Django 4.2.7 on 2023-12-05 13:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_connected_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
