# Generated by Django 4.2.7 on 2023-12-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_room_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player_list',
            field=models.JSONField(default=list),
        ),
    ]
