# Generated by Django 4.2.7 on 2023-12-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_room_player_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='player_list',
        ),
    ]
