# Generated by Django 4.2.7 on 2023-12-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_1', to='game.player'),
        ),
        migrations.AddField(
            model_name='room',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_2', to='game.player'),
        ),
        migrations.AddField(
            model_name='room',
            name='player_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_3', to='game.player'),
        ),
        migrations.AddField(
            model_name='room',
            name='player_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_4', to='game.player'),
        ),
        migrations.AddField(
            model_name='room',
            name='player_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_5', to='game.player'),
        ),
        migrations.AddField(
            model_name='room',
            name='player_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_6', to='game.player'),
        ),
        migrations.AddField(
            model_name='room',
            name='player_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_7', to='game.player'),
        ),
        migrations.AddField(
            model_name='room',
            name='player_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_8', to='game.player'),
        ),
    ]
