# Generated by Django 4.2.7 on 2023-12-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_player_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
