# Generated by Django 4.2.7 on 2023-12-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_player_is_master_room_master_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='room_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
