# Generated by Django 4.2.7 on 2023-12-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_player_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_connected',
            field=models.BooleanField(default=True),
        ),
    ]
