# Generated by Django 4.2.7 on 2023-12-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_remove_game_player1_remove_game_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='map',
            field=models.IntegerField(default=0),
        ),
    ]
