# Generated by Django 4.2.7 on 2023-11-28 18:19

import authentification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.CharField(blank=True, default=authentification.models.default_profile_image_path, max_length=255, null=True),
        ),
    ]
